// src/screens/NewTask/styles/newTaskStyles.ts
//
// Shared StyleSheet for the New Task screen. Extracted from NewTaskScreen
// in Phase 6 — used by ClientSection, ServiceSection, StagesSection,
// ScheduleSection, FieldRow, and the parent orchestrator.

import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const s = StyleSheet.create({
  safe:      { flex: 1, backgroundColor: theme.color.bgBase },
  container: { padding: theme.spacing.space4, gap: theme.spacing.space2, paddingBottom: 80 },
  section: {
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.lg,
    padding:         theme.spacing.space4,
    gap:             10,
    borderWidth:     1,
    borderColor:     theme.color.border,
    marginBottom:    theme.spacing.space3,
  },
  sectionTitle: { ...theme.typography.sectionDivider, marginBottom: 4 },
  fieldRowSelected: {
    flexDirection: 'row',
    alignItems:    'center',
    backgroundColor: theme.color.bgSurface,
    borderRadius:  theme.radius.lg,
    padding:       14,
    borderWidth:   1,
    borderColor:   theme.color.primary,
    gap:           6,
  },
  fieldRowSelectedHint:  { ...theme.typography.sectionDivider, color: theme.color.primary, marginBottom: 3 },
  fieldRowSelectedValue: { color: theme.color.textPrimary, fontSize: 16, fontWeight: '700' },
  fieldRow: {
    flexDirection:     'row',
    alignItems:        'center',
    justifyContent:    'space-between',
    backgroundColor:   theme.color.primary,
    borderRadius:      theme.radius.lg,
    paddingVertical:   14,
    paddingHorizontal: theme.spacing.space4,
  },
  fieldLabel:       { ...theme.typography.body, color: theme.color.white, fontWeight: '700', fontSize: 15 },
  fieldValue:       { flexDirection: 'row', alignItems: 'center', gap: 6, flex: 2 },
  fieldValueText:   { ...theme.typography.body, color: theme.color.textPrimary, flex: 1, textAlign: 'right' },
  fieldPlaceholder: { fontSize: 17, fontWeight: '700', color: theme.color.white, flex: 1, textAlign: 'right' },
  fieldChevron:     { color: theme.color.white, fontSize: 20, fontWeight: '700' },
  hint:             { ...theme.typography.label, color: theme.color.textMuted },
  addInlineBtn:     {
    alignSelf:       'stretch',
    marginTop:       theme.spacing.space2,
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.lg,
    paddingVertical: 12,
    alignItems:      'center',
    borderWidth:     1,
    borderColor:     theme.color.primary,
  },
  addInlineBtnText: { color: theme.color.primary, fontSize: 15, fontWeight: '700' },
  inlineForm: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    padding:         theme.spacing.space3,
    gap:             10,
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  inlineInput: {
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical: 10,
    color:           theme.color.textPrimary,
    fontSize:        theme.typography.body.fontSize,
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  selectedStages: { gap: 6 },
  stageRow: {
    flexDirection:   'row',
    alignItems:      'flex-start',
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    padding:         10,
    gap:             10,
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  stageIndex: {
    width:           24,
    height:          24,
    borderRadius:    12,
    backgroundColor: theme.color.primary + '33',
    justifyContent:  'center',
    alignItems:      'center',
  },
  stageIndexText:    { ...theme.typography.label, color: theme.color.primaryText, fontWeight: '700' },
  stageName:         { color: theme.color.textPrimary, fontSize: theme.typography.body.fontSize, fontWeight: '600' },
  stageActions:      { flexDirection: 'row', gap: theme.spacing.space2, alignItems: 'center' },
  stageDetailPanel: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    padding:         theme.spacing.space3,
    marginTop:       theme.spacing.space2,
    borderWidth:     1,
    borderColor:     theme.color.primary + '33',
  },
  stageDetailTab: {
    flex: 1, alignItems: 'center', paddingVertical: 6,
    borderRadius: theme.radius.sm, backgroundColor: theme.color.bgSurface,
  },
  stageDetailTabActive: { backgroundColor: theme.color.primary + '22' },
  stageDetailTabText: { ...theme.typography.label, color: theme.color.textMuted, fontWeight: '700' },
  // Save button at the bottom of the inline city/assignee picker
  stageDetailSaveBtn: {
    marginTop:       theme.spacing.space3,
    paddingVertical: 12,
    borderRadius:    theme.radius.md,
    backgroundColor: theme.color.primary,
    alignItems:      'center',
  },
  stageDetailSaveBtnText: {
    color:      theme.color.white,
    fontSize:   14,
    fontWeight: '700',
  },
  stageDetailSearch: {
    backgroundColor: theme.color.bgSurface, borderRadius: theme.radius.md,
    borderWidth: 1, borderColor: theme.color.border, color: theme.color.textPrimary,
    paddingHorizontal: theme.spacing.space3, paddingVertical: theme.spacing.space2,
    fontSize: 13, marginBottom: 6,
  },
  stageDetailItem: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.space3, paddingVertical: theme.spacing.space2,
    borderRadius: theme.radius.sm,
  },
  stageDetailItemActive: { backgroundColor: theme.color.primary + '18' },
  stageDetailItemText: { ...theme.typography.body, color: theme.color.textPrimary },
  // Inline create-new (city / contact) inside stage city/assignee picker
  inlineCreateBtn: {
    marginTop:    theme.spacing.space2,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space2 + 2,
    borderRadius:  theme.radius.md,
    borderWidth:   1,
    borderColor:   theme.color.primary,
    backgroundColor: theme.color.primary + '11',
    alignItems:    'center',
  },
  inlineCreateBtnText: {
    color:      theme.color.primary,
    fontSize:   13,
    fontWeight: '700',
  },
  inlineCreateForm: {
    marginTop:       theme.spacing.space2,
    padding:         theme.spacing.space3,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.primary + '55',
    backgroundColor: theme.color.bgSurface,
    gap:             theme.spacing.space2,
  },
  inlineCreateInput: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.sm,
    borderWidth:     1,
    borderColor:     theme.color.border,
    color:           theme.color.textPrimary,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space2,
    fontSize:        13,
  },
  inlineCreateActions: {
    flexDirection:  'row',
    justifyContent: 'flex-end',
    gap:            theme.spacing.space2,
    marginTop:      2,
  },
  inlineCancelBtn: {
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space2,
    borderRadius:      theme.radius.sm,
  },
  inlineCancelBtnText: {
    color:      theme.color.textSecondary,
    fontSize:   13,
    fontWeight: '600',
  },
  inlineSaveBtn: {
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   10,
    borderRadius:      theme.radius.md,
    backgroundColor:   theme.color.primary,
    alignItems:        'center' as const,
  },
  inlineSaveBtnText: {
    color:      theme.color.white,
    fontSize:   13,
    fontWeight: '700' as const,
  },
  stageArrow:        { color: theme.color.primary, fontSize: 18, fontWeight: '700', padding: 2 },
  stageRemove:       { color: theme.color.danger, fontSize: 16, padding: 2 },
  stageEdit:         { color: theme.color.textSecondary, fontSize: 15, padding: 2 },
  stageRenameConfirm: { color: theme.color.success, fontSize: 18, fontWeight: '700', padding: 2 },
  disabled: { opacity: 0.3 },
  addStopBtn: {
    borderWidth:     1.5,
    borderColor:     theme.color.primary + '55',
    borderStyle:     'dashed',
    borderRadius:    theme.radius.md,
    paddingVertical: theme.spacing.space3,
    alignItems:      'center',
    backgroundColor: theme.color.primary + '08',
  },
  addStopBtnText: { ...theme.typography.body, color: theme.color.primary, fontWeight: '600' },
  notesContainer: { gap: theme.spacing.space2 },
  notesInput: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical: 10,
    color:           theme.color.textPrimary,
    fontSize:        theme.typography.body.fontSize,
    borderWidth:     1,
    borderColor:     theme.color.border,
    minHeight:       80,
  },
  submitBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.lg,
    paddingVertical: 16,
    alignItems:      'center',
    marginTop:       theme.spacing.space2,
  },
  submitBtnDisabled: { opacity: 0.6 },
  activeFieldsContainer: { gap: 10 },
  activeFieldRow: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    padding:         10,
    gap:             6,
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  activeFieldHeader: {
    flexDirection:  'row',
    alignItems:     'center',
    justifyContent: 'space-between',
    marginBottom:   2,
  },
  activeFieldLabel:  { ...theme.typography.label, color: theme.color.textSecondary, fontWeight: '700' },
  activeFieldRemove: { color: theme.color.danger, fontSize: 16, padding: 2 },
  addFieldBtn: {
    borderWidth:     1.5,
    borderColor:     theme.color.primary + '55',
    borderStyle:     'dashed',
    borderRadius:    theme.radius.md,
    paddingVertical: 11,
    alignItems:      'center',
    backgroundColor: theme.color.primary + '08',
  },
  addFieldBtnText: { ...theme.typography.label, color: theme.color.primary, fontWeight: '700' },
  createdRow: {
    flexDirection:     'row',
    alignItems:        'center',
    justifyContent:    'space-between',
    paddingVertical:   6,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
    marginBottom:      4,
  },
  createdValue:  { color: theme.color.primary, fontSize: 13, fontWeight: '700' },
  optionalTag:   { ...theme.typography.caption, color: theme.color.textMuted, fontWeight: '400' },
  submitBtnText: { color: theme.color.white, fontSize: 16, fontWeight: '700' },
  newSvcStageList: { marginBottom: theme.spacing.space2 },
  newSvcStageRow:  { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  newSvcStageName: { flex: 1, color: theme.color.textSecondary, fontSize: 13, fontWeight: '600' },
  newSvcAddRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  newSvcPlusBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    width:           40,
    height:          40,
    justifyContent:  'center',
    alignItems:      'center',
    marginStart:     theme.spacing.space2,
  },
  newSvcPlusBtnText: { color: theme.color.white, fontSize: 22, lineHeight: 26 },
  modalOverlay: { flex: 1, backgroundColor: theme.color.overlayDark, justifyContent: 'center', padding: theme.spacing.space6 },
  editClientSheet: {
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.xl,
    padding:         20,
    borderWidth:     1,
    borderColor:     theme.color.border,
    ...theme.shadow.modal,
  },
  editClientTitle:      { ...theme.typography.body, color: theme.color.textPrimary, fontSize: 16, fontWeight: '700', marginBottom: 14 },
  editClientBtns:       { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 16 },
  editClientCancel:     { paddingHorizontal: theme.spacing.space4, paddingVertical: 10, marginEnd: 10 },
  editClientCancelText: { ...theme.typography.body, color: theme.color.textSecondary, fontWeight: '600' },
  editClientSave: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  editClientSaveText: { ...theme.typography.body, color: theme.color.white, fontWeight: '700' },

  // Required docs sheet button
  docsSheetBtn: {
    alignSelf: 'flex-start',
    backgroundColor: theme.color.primary + '18',
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.color.primary + '44',
    marginTop: 6,
    marginBottom: 4,
  },
  docsSheetBtnText: {
    color: theme.color.primaryText,
    fontSize: 13,
    fontWeight: '600',
  },
});
