// src/screens/Create/styles/createStyles.ts
//
// Shared StyleSheet for the Create tab. Extracted from CreateScreen — Phase 6.
//
// Used by CreateScreen.tsx and every modal in ./Create/components/*. Each
// component imports it directly instead of receiving an `s` prop, which lets
// the parent stop drilling the styles object through every modal.

import { StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const s = StyleSheet.create({
  safe:   { flex: 1, backgroundColor: theme.color.bgBase },
  scroll: { paddingBottom: theme.spacing.space10 },

  header: {
    paddingHorizontal: theme.spacing.space4,
    paddingTop:        theme.spacing.space5,
    paddingBottom:     theme.spacing.space3,
  },
  headerTitle: {
    ...theme.typography.heading,
    fontSize: 22,
  },

  sectionLabel: {
    ...theme.typography.sectionDivider,
    paddingHorizontal: theme.spacing.space4,
    paddingTop:        theme.spacing.space3,
    paddingBottom:     theme.spacing.space2,
  },

  // Quick action grid
  actionGrid: {
    flexDirection:     'row',
    flexWrap:          'wrap',
    paddingHorizontal: theme.spacing.space3,
    gap:               theme.spacing.space3,
  },
  actionCard: {
    width:             '47%',
    backgroundColor:   theme.color.bgSurface,
    borderRadius:      theme.radius.lg,
    borderWidth:       1,
    borderColor:       theme.color.border,
    paddingVertical:   theme.spacing.space5,
    paddingHorizontal: theme.spacing.space3,
    alignItems:        'center',
    gap:               theme.spacing.space2,
  },
  actionCardAccent: {
    borderColor:     theme.color.primary + '66',
    backgroundColor: theme.color.primaryDim,
  },
  actionIcon:       { fontSize: 28 },
  actionLabel:      { ...theme.typography.label, color: theme.color.textSecondary, fontWeight: '700', textAlign: 'center' },
  actionLabelAccent:{ color: theme.color.primaryText },

  // Manage rows
  manageList: {
    marginHorizontal: theme.spacing.space4,
    backgroundColor:  theme.color.bgSurface,
    borderRadius:     theme.radius.lg,
    borderWidth:      1,
    borderColor:      theme.color.border,
    overflow:         'hidden',
  },
  manageRow: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   theme.spacing.space3 + 2,
    minHeight:         theme.touchTarget.min,
    gap:               theme.spacing.space3,
  },
  manageRowBorder:  { borderBottomWidth: 1, borderBottomColor: theme.color.border },
  manageRowIcon:    { fontSize: theme.icon.md },
  manageRowLabel:   { flex: 1, ...theme.typography.body, fontWeight: '600' },
  manageRowBadge: {
    backgroundColor:   theme.color.primaryDim,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space2,
    paddingVertical:   theme.spacing.space1 - 1,
  },
  manageRowCount:   { ...theme.typography.label, color: theme.color.primaryText, fontWeight: '700' },
  manageRowArrow:   { ...theme.typography.heading, color: theme.color.textMuted },

  // Modals (shared with DashboardScreen pattern)
  modalOverlay: {
    flex:            1,
    backgroundColor: theme.color.overlayDark,
  },
  modalSheet: {
    backgroundColor:      theme.color.bgSurface,
    borderTopLeftRadius:  theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    borderWidth:          1,
    borderColor:          theme.color.border,
  },
  modalHeader: {
    flexDirection:     'row',
    alignItems:        'center',
    justifyContent:    'space-between',
    paddingHorizontal: theme.spacing.space4,
    paddingTop:        theme.spacing.space5,
    paddingBottom:     theme.spacing.space4,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
  },
  modalTitle:    { ...theme.typography.heading },
  modalSubtitle: { ...theme.typography.caption, marginTop: theme.spacing.space1 - 2 },
  modalClose: {
    ...theme.typography.heading,
    color:             theme.color.textMuted,
    paddingHorizontal: theme.spacing.space1,
    minWidth:          theme.touchTarget.min,
    minHeight:         theme.touchTarget.min,
    textAlign:         'center',
    textAlignVertical: 'center',
  },
  modalAddBtn: {
    backgroundColor:   theme.color.primaryDim,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space2 - 1,
    borderWidth:       1,
    borderColor:       theme.color.primary + '44',
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
  },
  modalAddBtnText: { ...theme.typography.label, color: theme.color.primaryText, fontWeight: '700' },
  modalImportBtn: {
    backgroundColor:   theme.color.infoDim,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space1 + 2,
    borderWidth:       1,
    borderColor:       theme.color.info + '55',
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
  },
  modalImportBtnText: { ...theme.typography.label, color: theme.color.info, fontWeight: '700' },
  // Import view
  importInstructions: {
    backgroundColor: theme.color.infoDim,
    borderRadius:    theme.radius.md,
    padding:         theme.spacing.space4,
    borderWidth:     1,
    borderColor:     theme.color.info + '44',
    gap:             theme.spacing.space2,
  },
  importInstructionsTitle: { fontSize: 16, color: theme.color.info, fontWeight: '700' },
  importInstructionsText:  { fontSize: 14, color: theme.color.textSecondary, lineHeight: 22 },
  importTextArea: {
    backgroundColor:   theme.color.bgSurface,
    borderRadius:      theme.radius.md,
    padding:           theme.spacing.space4,
    minHeight:         160,
    color:             theme.color.textPrimary,
    fontSize:          15,
    lineHeight:        22,
    borderWidth:       1,
    borderColor:       theme.color.border,
    textAlignVertical: 'top',
  },
  importPreviewBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    paddingVertical: theme.spacing.space4,
    alignItems:      'center',
  },
  importPreviewBtnText: { fontSize: 16, color: theme.color.white, fontWeight: '700' },
  importPreviewLabel:   { fontSize: 13, color: theme.color.textMuted, fontWeight: '700', letterSpacing: 0.8, marginTop: theme.spacing.space3 },
  importPreviewRow: {
    flexDirection:     'row',
    alignItems:        'center',
    gap:               theme.spacing.space3,
    paddingVertical:   theme.spacing.space3,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgBase,
  },
  importRowNum: {
    width:           30,
    height:          30,
    borderRadius:    15,
    backgroundColor: theme.color.bgSubtle,
    alignItems:      'center',
    justifyContent:  'center',
  },
  importRowNumText: { fontSize: 13, color: theme.color.textMuted, fontWeight: '700' },
  importRowName:    { fontSize: 16, color: theme.color.textPrimary, fontWeight: '700' },
  importRowSub:     { fontSize: 14, color: theme.color.textMuted, marginTop: 2 },
  modalBody: {
    padding: theme.spacing.space4,
    gap:     theme.spacing.space3,
  },
  modalInput: {
    backgroundColor:   theme.color.bgBase,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space3,
    color:             theme.color.textPrimary,
    ...theme.typography.body,
    borderWidth:       1,
    borderColor:       theme.color.border,
  },
  modalSaveBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    paddingVertical: theme.spacing.space3 + 1,
    alignItems:      'center',
    marginTop:       theme.spacing.space1,
  },
  modalSaveBtnDisabled: { opacity: 0.5 },
  modalSaveBtnText: {
    ...theme.typography.body,
    color:      theme.color.white,
    fontWeight: '700',
  },

  // Client form fields
  fieldsSectionLabel: {
    ...theme.typography.sectionDivider,
    marginTop:    theme.spacing.space2,
    marginBottom: theme.spacing.space3,
  },
  fieldDefLabel:  { ...theme.typography.label, color: theme.color.textSecondary, marginBottom: theme.spacing.space1 + 2 },
  fieldBoolRow: {
    flexDirection:     'row',
    alignItems:        'center',
    justifyContent:    'space-between',
    backgroundColor:   theme.color.bgBase,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space3,
    borderWidth:       1,
    borderColor:       theme.color.border,
  },
  fieldBoolText: { ...theme.typography.body, fontWeight: '600' },
  selectOption: {
    backgroundColor:   theme.color.bgBase,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space2,
    marginEnd:         theme.spacing.space2,
    borderWidth:       1,
    borderColor:       theme.color.border,
  },
  selectOptionActive:     { borderColor: theme.color.primary, backgroundColor: theme.color.primaryDim },
  selectOptionText:       { ...theme.typography.label, color: theme.color.textMuted },
  selectOptionTextActive: { color: theme.color.primaryText },
  dateBtn: {
    flexDirection:     'row',
    alignItems:        'center',
    backgroundColor:   theme.color.bgBase,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space3,
    borderWidth:       1,
    borderColor:       theme.color.border,
    minHeight:         theme.touchTarget.min,
  },
  dateBtnText:        { ...theme.typography.body, flex: 1 },
  dateBtnPlaceholder: { ...theme.typography.body, color: theme.color.textMuted, flex: 1 },
  dateBtnIcon:        { fontSize: theme.icon.md },
  inlineCalendarContainer: {
    marginTop:       theme.spacing.space1 + 2,
    borderRadius:    theme.radius.lg,
    overflow:        'hidden',
    borderWidth:     1,
    borderColor:     theme.color.border,
    backgroundColor: theme.color.bgBase,
  },
  clearDateBtn: {
    margin:          theme.spacing.space3,
    backgroundColor: theme.color.border,
    borderRadius:    theme.radius.md,
    paddingVertical: theme.spacing.space3,
    alignItems:      'center',
  },
  clearDateBtnText: { ...theme.typography.body, fontWeight: '600' },

  // Month/year picker
  monthYearPicker: {
    padding:          theme.spacing.space3,
    backgroundColor:  theme.color.bgBase,
  },
  monthYearPickerHeader: {
    flexDirection:  'row',
    alignItems:     'center',
    justifyContent: 'space-between',
    marginBottom:   theme.spacing.space3,
  },
  monthYearPickerYearInput: {
    ...theme.typography.heading,
    color:             theme.color.textPrimary,
    borderBottomWidth: 2,
    borderBottomColor: theme.color.primary,
    minWidth:          64,
    textAlign:         'center',
    paddingVertical:   theme.spacing.space1,
  },
  monthYearArrow:     { padding: theme.spacing.space2 },
  monthYearArrowText: { fontSize: 24, color: theme.color.primary, fontWeight: '700', lineHeight: 28 },
  monthGrid:          { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.space2 },
  monthGridItem: {
    width:           '22%',
    paddingVertical: theme.spacing.space2,
    borderRadius:    theme.radius.md,
    backgroundColor: theme.color.bgSurface,
    alignItems:      'center',
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  monthGridItemText: { ...theme.typography.label, color: theme.color.textPrimary },
  calHeaderBtn: {
    paddingVertical:   theme.spacing.space2,
    paddingHorizontal: theme.spacing.space3,
    alignSelf:         'center',
  },
  calHeaderText: { ...theme.typography.body, fontWeight: '700', color: theme.color.textPrimary },

  // Manage shared
  mgmtAddSectionLabel: { ...theme.typography.sectionDivider, marginBottom: theme.spacing.space2 + 2 },
  mgmtAddBlock: {
    padding:       theme.spacing.space3 + 2,
    paddingBottom: theme.spacing.space2,
    gap:           theme.spacing.space2,
  },
  mgmtPriceRow:   { flexDirection: 'row', gap: theme.spacing.space2 },
  mgmtAddBtn: {
    backgroundColor:   theme.color.primary,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space2 + 3,
    justifyContent:    'center',
    alignItems:        'center',
    minHeight:         theme.touchTarget.min,
  },
  mgmtAddBtnText:  { ...theme.typography.label, color: theme.color.white, fontWeight: '700' },
  mgmtSearchRow: {
    paddingHorizontal: theme.spacing.space4,
    paddingTop:        theme.spacing.space2 + 2,
    paddingBottom:     theme.spacing.space1 + 2,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgSurface,
  },
  mgmtSearchInput: {
    backgroundColor:   theme.color.bgBase,
    color:             theme.color.textPrimary,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space2 + 1,
    ...theme.typography.body,
    borderWidth:       1,
    borderColor:       theme.color.border,
  },
  mgmtClientRow: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space3 + 1,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgBase,
    gap:               theme.spacing.space3,
    minHeight:         theme.touchTarget.min,
  },
  mgmtClientAvatar: {
    width:           38,
    height:          38,
    borderRadius:    theme.radius.full,
    backgroundColor: theme.color.primaryDim,
    borderWidth:     1,
    borderColor:     theme.color.primary + '55',
    justifyContent:  'center',
    alignItems:      'center',
  },
  mgmtClientAvatarText: { ...theme.typography.body, color: theme.color.primaryText, fontWeight: '800' },
  mgmtEmpty: { ...theme.typography.body, color: theme.color.textMuted, textAlign: 'center', padding: theme.spacing.space8 },
  mgmtItemRow: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space3,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgBase,
    gap:               theme.spacing.space2,
    minHeight:         theme.touchTarget.min,
  },
  mgmtItemName:  { ...theme.typography.body, fontWeight: '600' },
  mgmtItemRef:   { ...theme.typography.caption, fontStyle: 'italic', marginTop: theme.spacing.space1 - 3 },
  stageCityChip: {
    marginTop:       4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius:    theme.radius.sm,
    backgroundColor: theme.color.bgBase,
    borderWidth:     1,
    borderColor:     theme.color.border,
  },
  stageCityChipText: { ...theme.typography.caption, color: theme.color.textMuted, fontSize: 12 },
  stageCityPanel: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.border,
    marginTop:       4,
    marginBottom:    4,
  },
  stageCityItem: {
    flexDirection:   'row',
    justifyContent:  'space-between',
    alignItems:      'center',
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgSurface,
  },
  stageCityItemActive: { backgroundColor: theme.color.primary + '14' },
  stageCityItemText:   { ...theme.typography.body, color: theme.color.textPrimary, flex: 1, flexWrap: 'wrap' },
  mgmtItemSub:   { ...theme.typography.caption, marginTop: theme.spacing.space1 - 2 },
  mgmtItemPrice: { ...theme.typography.caption, color: theme.color.primary, fontWeight: '600', marginTop: theme.spacing.space1 - 2 },
  mgmtEditBtn: {
    backgroundColor:   theme.color.border,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space2 + 2,
    paddingVertical:   theme.spacing.space1 + 2,
    minWidth:          theme.touchTarget.min,
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
    alignItems:        'center',
  },
  mgmtEditBtnText: { ...theme.typography.body, color: theme.color.textSecondary },
  mgmtDelBtn: {
    backgroundColor:   theme.color.dangerDim,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space2 + 2,
    paddingVertical:   theme.spacing.space1 + 2,
    minWidth:          theme.touchTarget.min,
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
    alignItems:        'center',
  },
  mgmtDelBtnText: { ...theme.typography.caption, color: theme.color.danger + 'a5' },
  mgmtEditRow: {
    flexDirection:   'row',
    gap:             theme.spacing.space2,
    padding:         theme.spacing.space3 + 2,
    paddingVertical: theme.spacing.space2 + 2,
    backgroundColor: theme.color.bgBase,
    alignItems:      'center',
  },
  mgmtSaveBtn: {
    backgroundColor:   theme.color.success,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space2,
    alignItems:        'center',
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
  },
  mgmtSaveBtnText:   { ...theme.typography.label, color: theme.color.white, fontWeight: '700' },
  mgmtCancelBtn: {
    backgroundColor:   theme.color.border,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space2 + 2,
    paddingVertical:   theme.spacing.space2,
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
  },
  mgmtCancelBtnText: { ...theme.typography.label, color: theme.color.textSecondary },
  mgmtReqBtn: {
    backgroundColor:   theme.color.successDim,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space2 + 2,
    paddingVertical:   theme.spacing.space1 + 2,
    borderWidth:       1,
    borderColor:       theme.color.success + '44',
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
  },
  mgmtReqBtnText: { ...theme.typography.caption, color: theme.color.success, fontWeight: '700' },

  // Inline panels (service stages + stage requirements)
  inlinePanel: {
    backgroundColor:   theme.color.bgBase,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
    paddingBottom:     theme.spacing.space2,
  },
  inlinePanelLabel: {
    ...theme.typography.sectionDivider,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingTop:        theme.spacing.space2 + 2,
    paddingBottom:     theme.spacing.space1 + 2,
  },
  inlinePanelEmpty: { ...theme.typography.caption, color: theme.color.textMuted, paddingHorizontal: theme.spacing.space3 + 2, paddingVertical: theme.spacing.space2 },
  inlineStageRow: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space1 + 2,
    gap:               theme.spacing.space2,
  },
  inlineStageOrder: { ...theme.typography.caption, color: theme.color.textMuted, minWidth: 18 },
  inlineStageName:  { ...theme.typography.body, fontSize: 13, flex: 1 },
  inlineStageBtn: {
    backgroundColor:   theme.color.border,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space2,
    paddingVertical:   theme.spacing.space1,
    minWidth:          28,
    minHeight:         28,
    justifyContent:    'center',
    alignItems:        'center',
  },
  inlineStageBtnText: { ...theme.typography.label, color: theme.color.textSecondary },
  inlineAddRow: {
    flexDirection:     'row',
    gap:               theme.spacing.space2,
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingTop:        theme.spacing.space2,
    paddingBottom:     theme.spacing.space1,
  },
  inlineAddBtn: {
    backgroundColor:   theme.color.primary,
    borderRadius:      theme.radius.sm,
    paddingHorizontal: theme.spacing.space3,
    minWidth:          40,
    minHeight:         theme.touchTarget.min,
    justifyContent:    'center',
    alignItems:        'center',
  },
  inlineAddBtnText: { ...theme.typography.heading, color: theme.color.white, fontSize: 18 },
  inlinePill: {
    backgroundColor:   theme.color.primaryDim,
    borderRadius:      theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   theme.spacing.space1 + 2,
    marginEnd:         theme.spacing.space2,
    borderWidth:       1,
    borderColor:       theme.color.primary + '44',
  },
  inlinePillText: { ...theme.typography.label, color: theme.color.primaryText },
  inlineReqRow: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: theme.spacing.space3 + 2,
    paddingVertical:   theme.spacing.space1 + 2,
    gap:               theme.spacing.space2,
  },
  inlineReqTitle: { ...theme.typography.body, fontSize: 13, flex: 1 },

  // ── Network styles ────────────────────────────────────────
  netContactCard: {
    flexDirection:   'row',
    alignItems:      'flex-start',
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   theme.spacing.space3,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
    gap:             theme.spacing.space3,
  },
  netContactName:    { ...theme.typography.body, fontWeight: '700', marginBottom: 2 },
  netContactPhone:   { ...theme.typography.caption, color: theme.color.primary, marginBottom: 1 },
  netContactRef:     { ...theme.typography.caption, color: theme.color.textMuted, fontStyle: 'italic', marginBottom: 1 },
  netContactCity:     { ...theme.typography.caption, color: theme.color.textSecondary },
  netContactFieldVal: { ...theme.typography.caption, color: theme.color.textMuted, marginTop: 1 },
  netContactActions: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  netActionBtn:      { padding: 6 },
  netActionEdit:     { color: theme.color.primary, fontSize: 16 },
  netActionDelete:   { color: theme.color.textMuted, fontSize: 15 },
  netAddBtn: {
    margin:          theme.spacing.space4,
    paddingVertical: theme.spacing.space3,
    borderRadius:    theme.radius.md,
    backgroundColor: theme.color.primary + '18',
    borderWidth:     1,
    borderColor:     theme.color.primary + '44',
    alignItems:      'center',
  },
  netAddBtnText: { ...theme.typography.body, color: theme.color.primary, fontWeight: '700' },
  netAddFieldBtn: {
    borderWidth:     1,
    borderColor:     theme.color.border,
    borderRadius:    theme.radius.md,
    paddingVertical: theme.spacing.space3,
    alignItems:      'center',
    backgroundColor: theme.color.bgBase,
  },
  netAddFieldBtnText: { ...theme.typography.label, color: theme.color.primary, fontWeight: '700' },
  netFieldPickerItem: {
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'space-between',
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   10,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
  },
  netFieldPickerType: { ...theme.typography.caption, color: theme.color.textMuted, fontStyle: 'italic' },
  netForm: {
    borderTopWidth:  1,
    borderTopColor:  theme.color.border,
    padding:         theme.spacing.space4,
    gap:             10,
    backgroundColor: theme.color.bgBase,
  },
  netFormTitle:  { ...theme.typography.label, fontWeight: '700', color: theme.color.textSecondary },
  netInput: {
    backgroundColor:  theme.color.bgSurface,
    borderRadius:     theme.radius.md,
    borderWidth:      1,
    borderColor:      theme.color.border,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:  10,
    ...theme.typography.body,
    color:            theme.color.textPrimary,
  },
  netCityTrigger: {
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'space-between',
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.border,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   10,
  },
  netCityTriggerText: { ...theme.typography.body, color: theme.color.textMuted, flex: 1 },
  netCityDropdown: {
    backgroundColor: theme.color.bgSurface,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.border,
    overflow:        'hidden',
  },
  netCitySearch: {
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   8,
    ...theme.typography.body,
    color:             theme.color.textPrimary,
  },
  netCityItem: {
    flexDirection:   'row',
    alignItems:      'center',
    justifyContent:  'space-between',
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   10,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
  },
  netCityItemActive: { backgroundColor: theme.color.primary + '11' },
  netCityItemText:   { ...theme.typography.body, color: theme.color.textPrimary, flex: 1 },
  netFormActions:  { flexDirection: 'row', gap: 10 },
  netCancelBtn: {
    flex:            0,
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   theme.spacing.space3,
    borderRadius:    theme.radius.md,
    backgroundColor: theme.color.bgSurface,
    borderWidth:     1,
    borderColor:     theme.color.border,
    alignItems:      'center',
  },
  netCancelBtnText: { ...theme.typography.body, color: theme.color.textSecondary, fontWeight: '600' },
  netSaveBtn: {
    flex:            1,
    paddingVertical: theme.spacing.space3,
    borderRadius:    theme.radius.md,
    backgroundColor: theme.color.primary,
    alignItems:      'center',
  },
  netSaveBtnText: { ...theme.typography.body, color: theme.color.white, fontWeight: '700' },

  // ── Service Documents styles ──────────────────────────────
  docSvcCard: {
    marginHorizontal: theme.spacing.space3,
    marginBottom:     theme.spacing.space3,
    backgroundColor:  theme.color.bgSurface,
    borderRadius:     theme.radius.lg,
    borderWidth:      1,
    borderColor:      theme.color.border,
    overflow:         'hidden',
  },
  docSvcRow: {
    flexDirection:   'row',
    alignItems:      'center',
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   theme.spacing.space3 + 2,
    gap:             theme.spacing.space2,
  },
  docSvcName:  { flex: 1, ...theme.typography.body, fontWeight: '700' },
  docSvcBadge: { ...theme.typography.caption, color: theme.color.success, fontWeight: '700' },
  docSvcArrow: { ...theme.typography.caption, color: theme.color.textMuted },
  docListPanel: {
    borderTopWidth: 1,
    borderTopColor: theme.color.border,
    paddingBottom:  theme.spacing.space2,
  },
  docEmpty: { ...theme.typography.caption, color: theme.color.textMuted, padding: theme.spacing.space3, paddingBottom: theme.spacing.space1 },
  docRow: {
    flexDirection:   'row',
    alignItems:      'center',
    paddingHorizontal: theme.spacing.space4,
    paddingVertical:   10,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
    gap:             theme.spacing.space2,
  },
  docNumber:      { ...theme.typography.caption, color: theme.color.textMuted, minWidth: 20 },
  docCheck:       { fontSize: 18, color: theme.color.textMuted },
  docCheckDone:   { color: theme.color.success },
  docTitle:       { flex: 1, ...theme.typography.body },
  docTitleDone:   { textDecorationLine: 'line-through', color: theme.color.textMuted },
  docDelete:      { color: theme.color.textMuted, fontSize: 14, padding: 4 },
  docAddRow: {
    flexDirection:   'row',
    alignItems:      'center',
    marginHorizontal: theme.spacing.space3,
    marginTop:       theme.spacing.space2,
    gap:             8,
  },
  docAddInput: {
    flex:            1,
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.border,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   8,
    ...theme.typography.body,
    color:           theme.color.textPrimary,
  },
  docAddBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    paddingHorizontal: theme.spacing.space3,
    paddingVertical:   8,
    alignItems:      'center',
  },
  docAddBtnText:  { color: theme.color.white, fontWeight: '700', fontSize: 16 },

  // Sub-requirement styles
  docReqBadge: {
    backgroundColor: theme.color.primary + '33',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 20,
    alignItems: 'center',
  },
  docReqBadgeText: {
    color: theme.color.primaryText,
    fontSize: 10,
    fontWeight: '700',
  },
  docReqPanel: {
    backgroundColor: theme.color.bgBase,
    marginHorizontal: theme.spacing.space2,
    marginBottom: theme.spacing.space2,
    borderRadius: theme.radius.md,
    padding: theme.spacing.space2,
    borderWidth: 1,
    borderColor: theme.color.border,
  },
  docSubReqRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.border,
  },
  docSubReqBullet: {
    color: theme.color.primary,
    fontSize: 16,
    lineHeight: 20,
  },
  docSubReqTitle: {
    flex: 1,
    color: theme.color.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  docReqEmpty: {
    color: theme.color.textMuted,
    fontSize: 12,
    padding: theme.spacing.space2,
    textAlign: 'center',
  },

  docResetBtn: {
    marginHorizontal: theme.spacing.space3,
    marginTop:        theme.spacing.space2,
    paddingVertical:  8,
    alignItems:       'center',
    borderRadius:     theme.radius.md,
    borderWidth:      1,
    borderColor:      theme.color.border,
  },
  docResetBtnText: { ...theme.typography.caption, color: theme.color.textMuted, fontWeight: '600' },

  // Document Excel import
  docImportToggleBtn: {
    backgroundColor: theme.color.bgBase,
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.border,
    paddingHorizontal: 10,
    paddingVertical:   8,
    alignItems:      'center',
    justifyContent:  'center',
  },
  docImportToggleBtnText: { fontSize: 16 },
  docImportPanel: {
    marginHorizontal: theme.spacing.space3,
    marginTop:        theme.spacing.space2,
    backgroundColor:  theme.color.bgBase,
    borderRadius:     theme.radius.md,
    borderWidth:      1,
    borderColor:      theme.color.border,
    padding:          theme.spacing.space3,
    gap:              8,
  },
  docImportLabel: { ...theme.typography.caption, color: theme.color.textMuted, fontWeight: '700', marginBottom: 4 },
  docImportTextArea: {
    backgroundColor:  theme.color.bgSurface,
    borderRadius:     theme.radius.sm,
    borderWidth:      1,
    borderColor:      theme.color.border,
    padding:          10,
    minHeight:        80,
    color:            theme.color.textPrimary,
    ...theme.typography.body,
    textAlignVertical: 'top',
  },
  docImportPreviewBtn: {
    backgroundColor: theme.color.primary,
    borderRadius:    theme.radius.md,
    paddingVertical: 8,
    alignItems:      'center',
  },
  docImportPreviewBtnText: { color: theme.color.white, fontWeight: '700', fontSize: 13 },
  docImportPreviewRow: {
    flexDirection: 'row',
    alignItems:    'center',
    gap:           8,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.bgSurface,
  },
  docImportPreviewTitle: { ...theme.typography.body, color: theme.color.textPrimary, flex: 1 },
  docImportConfirmBtn: {
    backgroundColor: theme.color.success,
    borderRadius:    theme.radius.md,
    paddingVertical: 8,
    alignItems:      'center',
    marginTop:       4,
  },
  docImportConfirmBtnText: { color: theme.color.white, fontWeight: '700', fontSize: 13 },

  // ID / QR scanner button (in New Client modal header)
  scanIdBtn: {
    backgroundColor: theme.color.primary + '22',
    borderRadius:    theme.radius.md,
    borderWidth:     1,
    borderColor:     theme.color.primary + '66',
    paddingHorizontal: 10,
    paddingVertical:   6,
  },
  scanIdBtnText: { color: theme.color.primary, fontWeight: '700', fontSize: 12 },
});
