// src/screens/TaskDetail/hooks/useTaskActions.ts
//
// First slice of the action-handler extraction (Phase 5 of the TaskDetail
// refactor — see ../README.md). This pulls the FILE-LEVEL handlers out of
// the monolith because they have the cleanest inputs/outputs:
//
//   • handlePhonePress       — Alert with Call / WhatsApp links
//   • handleShareWhatsApp    — opens wa.me with a status message
//   • handleShareDocsWhatsApp — opens wa.me with the required-docs checklist
//   • handleDuplicateTask    — clones the file (new file_id, all stages reset)
//
// These handlers all READ task state but don't mutate it (or mutate via a
// single setter passed in). Other handler groups — comments / voice notes /
// stage CRUD / transactions — touch many pieces of state and will be
// extracted in later sessions.
//
// Pattern: the hook gets context (auth, navigation, t) from React hooks
// directly; everything else (the task itself, sheet state, setters) is
// passed in via the options object so the hook stays a pure consumer.
//
// To extend in a future session, add another handler in the same shape:
//   1. Take the function out of TaskDetailScreen.tsx
//   2. Identify what state it reads / writes
//   3. Add the read state to UseTaskActionsOptions; add the writers as
//      callback args (setX, setY)
//   4. Drop the inline copy and destructure the new handler from the hook

import { Alert, Linking } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';

import supabase from '../../../lib/supabase';
import { useAuth } from '../../../hooks/useAuth';
import { useTranslation } from '../../../lib/i18n';
import { Task, DashboardStackParamList } from '../../../types';

// Local helper — identical to the one at the top of TaskDetailScreen.tsx.
// Inlined here so the hook is self-contained; we'll deduplicate when more
// utility functions get extracted.
function formatDateOnly(iso: string) {
  const [y, m, d] = iso.split('T')[0].split('-');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${parseInt(d)} ${months[parseInt(m) - 1]} ${parseInt(y)}`;
}

type Nav = NativeStackNavigationProp<DashboardStackParamList>;

export interface UseTaskActionsOptions {
  /** The currently-loaded task. Handlers no-op when null. */
  task: Task | null;
  /** Service-document rows currently displayed in the Required Docs sheet. */
  sheetDocs: any[];
  /** Sub-requirements per service-document, keyed by doc id. */
  sheetDocReqs: Record<string, any[]>;
  /** Setter for the duplicate-in-progress spinner shown on the duplicate button. */
  setDuplicating: (b: boolean) => void;
}

export interface UseTaskActionsReturn {
  handlePhonePress:        (phone: string, name?: string) => void;
  handleShareWhatsApp:     () => void;
  handleShareDocsWhatsApp: () => void;
  handleDuplicateTask:     () => void;
}

export function useTaskActions(opts: UseTaskActionsOptions): UseTaskActionsReturn {
  const { task, sheetDocs, sheetDocReqs, setDuplicating } = opts;
  const { teamMember } = useAuth();
  const { t } = useTranslation();
  const navigation = useNavigation<Nav>();

  // ─── Phone-number long-press menu (Call / WhatsApp / Cancel) ───────────
  const handlePhonePress = (phone: string, name?: string) => {
    const clean = phone.replace(/[^0-9+]/g, '');
    Alert.alert(name ?? phone, phone, [
      { text: '📞 Phone Call', onPress: () => Linking.openURL(`tel:${clean}`) },
      { text: '💬 WhatsApp',   onPress: () => Linking.openURL(`https://wa.me/${clean.replace(/^\+/, '')}`) },
      { text: 'Cancel', style: 'cancel' },
    ]);
  };

  // ─── Share file status via WhatsApp ────────────────────────────────────
  // Composes an Arabic-language status message (client / service / status /
  // stage list / notes) and opens wa.me. Footer includes "Generated by …"
  // line + the GovPilot branding line.
  const handleShareWhatsApp = () => {
    if (!task) return;
    const stops = [...(task.route_stops ?? [])].sort((a, b) => a.stop_order - b.stop_order);
    const stageLines = stops
      .map((s, i) => `  ${i + 1}. ${s.ministry?.name ?? 'Stage'}: ${s.status}`)
      .join('\n');

    const parts: string[] = [
      `📁 *تحديث ملف*`,
      `العميل: ${task.client?.name ?? '-'}`,
      `الخدمة: ${task.service?.name ?? '-'}`,
      `الحالة: *${task.current_status}*`,
    ];
    if (task.due_date) parts.push(`تاريخ الاستحقاق: ${formatDateOnly(task.due_date)}`);
    if (stops.length > 0) parts.push(`\n*المراحل:*\n${stageLines}`);
    if (task.notes) parts.push(`\nملاحظات: ${task.notes}`);
    if (teamMember?.name) parts.push(`\n_Generated by ${teamMember.name}_`);
    parts.push('_GovPilot, Powered by KTS_');

    const msg = parts.join('\n');
    Linking.openURL(`https://wa.me/?text=${encodeURIComponent(msg)}`);
  };

  // ─── Share required-docs checklist via WhatsApp ────────────────────────
  // Checked docs render with strikethrough (~~~) so the recipient sees what's
  // already collected vs what's still pending. Sub-requirements follow the
  // same pattern.
  const handleShareDocsWhatsApp = () => {
    if (!task?.service || sheetDocs.length === 0) return;
    const lines = [`📋 *${task.service.name}* — Required Documents:\n`];
    sheetDocs.forEach((doc: any, idx: number) => {
      if (doc.is_checked) {
        lines.push(`~${idx + 1}. ${doc.title}~`);
        (sheetDocReqs[doc.id] ?? []).forEach((r: any) => lines.push(`   ~• ${r.title}~`));
      } else {
        lines.push(`${idx + 1}. *${doc.title}*`);
        (sheetDocReqs[doc.id] ?? []).forEach((r: any) => lines.push(`   • ${r.title}`));
      }
    });
    if (teamMember?.name) lines.push(`\n_Generated by ${teamMember.name}_`);
    lines.push('_GovPilot, Powered by KTS_');
    const msg = encodeURIComponent(lines.join('\n'));
    Linking.openURL(`https://wa.me/?text=${msg}`).catch(() =>
      Alert.alert(t('error'), t('somethingWrong'))
    );
  };

  // ─── Duplicate file ────────────────────────────────────────────────────
  // Clones tasks row + task_route_stops with all stages reset to "Pending"
  // and current_status reset to "Submitted". Preserves: client, service,
  // assignees (team + ext), notes, prices, per-stage city_id. Resets:
  // due_date, archive flag, status_updates audit (a fresh "Submitted" row
  // gets inserted to seed the new file's history).
  const handleDuplicateTask = () => {
    if (!task) return;
    Alert.alert(
      'Duplicate File',
      `Create a new file for ${task.client?.name} with the same service and stages?\n\nThe new file will start as "Submitted" with all stages reset to "Pending".`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Duplicate',
          onPress: async () => {
            setDuplicating(true);
            try {
              const now = new Date().toISOString();
              const { data: newTask, error: taskErr } = await supabase
                .from('tasks')
                .insert({
                  client_id:       task.client_id,
                  service_id:      task.service_id,
                  assigned_to:     task.assigned_to     ?? null,
                  ext_assignee_id: task.ext_assignee_id ?? null,
                  current_status:  'Submitted',
                  due_date:        null,
                  notes:           task.notes           ?? null,
                  price_usd:       task.price_usd       ?? 0,
                  price_lbp:       task.price_lbp       ?? 0,
                  is_archived:     false,
                  created_at:      now,
                  updated_at:      now,
                  org_id:          teamMember?.org_id   ?? null,
                })
                .select()
                .single();
              if (taskErr) throw taskErr;

              const sortedStops = [...(task.route_stops ?? [])].sort((a, b) => a.stop_order - b.stop_order);
              if (sortedStops.length > 0) {
                const newStops = sortedStops.map((s, idx) => ({
                  task_id:    newTask.id,
                  ministry_id: s.ministry_id,
                  stop_order: idx + 1,
                  status:     'Pending',
                  city_id:    s.city_id ?? null,
                }));
                const { error: stopsErr } = await supabase.from('task_route_stops').insert(newStops);
                if (stopsErr) throw stopsErr;
              }

              await supabase.from('status_updates').insert({
                task_id:    newTask.id,
                updated_by: teamMember?.id,
                new_status: 'Submitted',
              });

              setDuplicating(false);
              Alert.alert(t('duplicate'), t('savedSuccess'), [
                {
                  text: 'Open New File',
                  onPress: () => {
                    // Bounce through the Dashboard so its useFocusEffect refreshes
                    // (the new task isn't in its in-memory list yet), then push
                    // the new TaskDetail on top.
                    navigation.navigate('DashboardHome');
                    setTimeout(() => navigation.navigate('TaskDetail', { taskId: newTask.id }), 50);
                  },
                },
                { text: 'Stay Here', style: 'cancel' },
              ]);
            } catch (e: any) {
              setDuplicating(false);
              Alert.alert(t('error'), e.message ?? t('somethingWrong'));
            }
          },
        },
      ]
    );
  };

  return {
    handlePhonePress,
    handleShareWhatsApp,
    handleShareDocsWhatsApp,
    handleDuplicateTask,
  };
}
